### ISSUE TITLE
spearman_affwild2.pkl and load pre-trained model on Aff-Wild2

### ISSUE THREAD

**Issue by GJandy** [PanosAntoniadis/emotion-gcn#10]
@PanosAntoniadis  Can you share the the spearman_affwild2.pkl file? or it 's just as same as spearman_affectnet.pkl file.

and for the pre-trained model on Aff-Wild2,  I cannot find it in your given link.

**Comment by PanosAntoniadis** [comment]
Hello @GJandy  ! Thanks for your interest in my research!

Unfortunately, the `spearman_affwild2.pkl` file is not available. However, you can compute the adjacency matrix using the equations 3, 4, 5 and 6 from the paper. In case you have any question, please let me know.

Regarding the pre-trained model on Aff-Wild2. it is available in the given link (https://drive.google.com/drive/folders/1BUUOKelxNtkIETrb93nb6VIP-J4bT7Os?usp=sharing) in the folder affwild2.

**Comment by GJandy** [comment]
@PanosAntoniadis  Thank you.
