### ISSUE TITLE
test code

### ISSUE THREAD

**Issue by Yiqin-Luo** [PanosAntoniadis/emotion-gcn#2]
Hello！ Could you please send me the test code if possible?Thank you very much！Best wishes！

**Comment by coder-xinxiaohai** [comment]
hi I've been reading this paper, too，could you tell me how to create files named ''emb.pkl'and''adj.pkl''?

**Comment by coder-xinxiaohai** [comment]
> hi I've been reading this paper, too，could you tell me how to create files named ''emb.pkl'and''adj.pkl''?

ok,I have solved this problem
