### ISSUE TITLE
The 'inp' in the net

### ISSUE THREAD

**Issue by ymliu17** [PanosAntoniadis/emotion-gcn#4]
1. Does it mean that we can only use the pre-defined embedding for this network?
2. I don't understand the purpose of 'inp = inp[0]' in Emotion_gcn module. When I try to predict only one image, a dismatch error raises. After I annotate this line, it seems work.

**Comment by jakobkruse1** [comment]
I am also confused by this part. Where does the `inp` come from and how can we obtain the `emb.pkl` file? Clarification would be very much appreciated @PanosAntoniadis :+1:

**Comment by PanosAntoniadis** [comment]
Hello @jakobkruse1 ! The `inp` holds the embeddings and can be downloaded from the link in README (2nd bullet [here](https://github.com/PanosAntoniadis/emotion-gcn#preparation)).

**Comment by PanosAntoniadis** [comment]
Hello @lyocean17 ! Sorry for the delay. You can use any pre-defined embedding you want if you bring them in the same format as the 300-dimensional GloVe vectors that I used. In case the word embeddings you want to use have a different dimensionality, you should modify the `in_channel` parameter in `Emotion-GCN`. 

As for `inp = inp[0]`, this has to do with the format of the vectors you use.

**Comment by ymliu17** [comment]
> Hello @lyocean17 ! Sorry for the delay. You can use any pre-defined embedding you want if you bring them in the same format as the 300-dimensional GloVe vectors that I used. In case the word embeddings you want to use have a different dimensionality, you should modify the `in_channel` parameter in `Emotion-GCN`.
> 
> As for `inp = inp[0]`, this has to do with the format of the vectors you use.

Thanks @PanosAntoniadis！
