### ISSUE TITLE
spearman_affwild2.pkl

### ISSUE THREAD

**Issue by ymliu17** [PanosAntoniadis/emotion-gcn#5]
could you please also share the spearman_affwild2.pkl file?

**Comment by coder-xinxiaohai** [comment]
hi I've been reading this paper, too，could you tell me how to create files named ''emb.pkl'and''adj.pkl''?

**Comment by coder-xinxiaohai** [comment]
> hi I've been reading this paper, too，could you tell me how to create files named ''emb.pkl'and''adj.pkl''?

ok,I have solved this problem

**Comment by strangerfaker** [comment]
> > hi I've been reading this paper, too，could you tell me how to create files named ''emb.pkl'and''adj.pkl''?
> 
> ok,I have solved this problem
>Can we communicate? I also want to reproduce this article, but I encounter some problems, I can exchange contact information

**Comment by strangerfaker** [comment]
> > hi I've been reading this paper, too，could you tell me how to create files named ''emb.pkl'and''adj.pkl''?


> Can we communicate? I also want to reproduce this article, but I encounter some problems, I can exchange contact information

**Comment by strangerfaker** [comment]
> hi I've been reading this paper, too，could you tell me how to create files named ''emb.pkl'and''adj.pkl''?

Can we communicate? I also want to reproduce this article, but I encounter some problems, I can exchange contact information
