### ISSUE TITLE
load pre-trained model 

### ISSUE THREAD

**Issue by noctilucas1** [PanosAntoniadis/emotion-gcn#7]
Sorry for my lack of knowledge... 
 
But, how can I load the model with the pre-trained weights?

**Comment by PanosAntoniadis** [comment]
Hello @noctilucas1 ,

First, you should download the pre-trained models from [here](https://drive.google.com/drive/folders/1BUUOKelxNtkIETrb93nb6VIP-J4bT7Os?usp=sharing). 
Then, you have to load the model based on [this tutorial](https://pytorch.org/tutorials/beginner/saving_loading_models.html#saving-loading-a-general-checkpoint-for-inference-and-or-resuming-training). 

For example, if you want to load `affectnet/emotion_gcn_l2t01p05` you run:

```python
from models import Emotion_GCN

checkpoint = torch.load("affectnet/emotion_gcn_l2t01p05")
model = Emotion_GCN(adj_file="path_to_the_pickle_file", input_size=227)
model.load_state_dict(checkpoint['model_state_dict'])

```
